language: php

cache:
    apt: true
    directories:
        - vendor
        - bin

php:
    - 5.3
    - 5.5

install:
    - composer install --dev --prefer-source

before_script:
    - php -S localhost:8888 -t features/bootstrap/web 2> /dev/null &

script:
    - bin/atoum
    - bin/behat -f progress

notifications:
    email:
        recipients:
            - ci@verylastroom.com
        on_success: change
        on_failure: change
